Repository STEP-Pod-Capstone-Project/Capstone-Project, pull requests merged in 2020-07, with the labels that each got.

#33 New Client ID for Google Login and Fix for Search feature
  capstone-frontend/src/components/Login.jsx
  capstone-frontend/src/components/Navbar.jsx
Labels: Core Feature

#32 Club flow: firebase
  capstone-backend/src/main/java/com/google/sps/data/Club.java
  capstone-backend/src/main/java/com/google/sps/servlets/ClubServlet.java
  capstone-backend/src/test/java/com/google/sps/data/ClubTest.java
  capstone-frontend/package-lock.json
  capstone-frontend/package.json
  capstone-frontend/src/components/ClubPage.jsx
Labels: Core Feature

#34 UserServlet: Authentication and Firestore
  .gitignore
  .gitpod.Dockerfile
  .gitpod.yml
  README.md
  capstone-backend/.factorypath
  capstone-backend/src/main/java/com/google/sps/data/User.java
  capstone-backend/src/main/java/com/google/sps/servlets/UserServlet.java
  capstone-backend/src/main/java/com/google/sps/servlets/Utility.java
  capstone-backend/src/test/java/com/google/sps/data/BookListTest.java
  capstone-backend/src/test/java/com/google/sps/data/UserTest.java
  capstone-backend/src/test/java/com/google/sps/data/VolumeDataTest.java
  capstone-frontend/package-lock.json
  capstone-frontend/public/index.html
  capstone-frontend/src/App.test.jsx
  capstone-frontend/src/components/Login.jsx
Labels: Core Feature, Ready for Review

#50 Firebase Update
  .gitpod.Dockerfile
  .gitpod.yml
  capstone-backend/src/main/java/com/google/sps/servlets/UserServlet.java
  capstone-backend/src/main/java/com/google/sps/servlets/Utility.java
  capstone-backend/src/main/webapp/.gitignore
  capstone-frontend/package-lock.json
Labels: Core Feature, Ready for Review

#46 [UI] Book Search Tile
  capstone-frontend/src/BookSearchTile.test.js
  capstone-frontend/src/components/BookSearchList.jsx
  capstone-frontend/src/components/BookSearchTile.jsx
  capstone-frontend/src/styles/BookSearchTile.css
Labels: Core Feature

#41 Abstract put
  capstone-backend/src/main/java/com/google/sps/servlets/ClubServlet.java
  capstone-backend/src/main/java/com/google/sps/servlets/Utility.java
  capstone-frontend/src/components/CreateClub.jsx
Labels: Core Feature

#51 Abstract post
  capstone-backend/src/main/java/com/google/sps/servlets/ClubServlet.java
  capstone-backend/src/main/java/com/google/sps/servlets/Utility.java
  capstone-frontend/src/components/CreateClub.jsx
Labels: Core Feature

#53 Add Search Icon to search Navbar
  capstone-frontend/public/images/default_account.png
  capstone-frontend/public/images/search_icon.png
  capstone-frontend/src/components/Navbar.jsx
Labels: Additional Feature, Ready for Review

#52 Community/Group Backend Object
  capstone-backend/src/main/java/com/google/sps/data/Club.java
  capstone-backend/src/main/java/com/google/sps/data/Community.java
  capstone-backend/src/main/java/com/google/sps/data/Group.java
  capstone-backend/src/test/java/com/google/sps/CommunityTest.java
  capstone-backend/src/test/java/com/google/sps/data/ClubTest.java
  capstone-backend/src/test/java/com/google/sps/data/GroupTest.java
Labels: Core Feature

#30 BookList Implementation
  capstone-backend/src/main/java/com/google/sps/data/BookList.java
  capstone-backend/src/main/java/com/google/sps/servlets/BookListServlet.java
  capstone-backend/src/main/java/com/google/sps/servlets/ClubServlet.java
  capstone-backend/src/main/java/com/google/sps/servlets/SearchServlet.java
  capstone-backend/src/test/java/com/google/sps/data/BookListTest.java
  capstone-backend/src/test/java/com/google/sps/data/CommunityTest.java
  capstone-frontend/src/BookSearchTile.test.js
  capstone-frontend/src/components/BookSearchList.jsx
  capstone-frontend/src/components/BookSearchTile.jsx
  capstone-frontend/src/components/Login.jsx
  capstone-frontend/src/components/MyLists.js
  capstone-frontend/src/components/MyLists.jsx
Labels: Core Feature, Ready for Review

#55 Generalized delete helper function
  capstone-backend/src/main/java/com/google/sps/servlets/ClubServlet.java
  capstone-backend/src/main/java/com/google/sps/servlets/Utility.java
  capstone-frontend/src/components/ClubPage.jsx
Labels: Core Feature

#58 Assignments and Comments: objects and servlets
  capstone-backend/src/main/java/com/google/sps/data/Assignment.java
  capstone-backend/src/main/java/com/google/sps/data/Club.java
  capstone-backend/src/main/java/com/google/sps/data/Comment.java
  capstone-backend/src/main/java/com/google/sps/data/Community.java
  capstone-backend/src/main/java/com/google/sps/data/Group.java
  capstone-backend/src/main/java/com/google/sps/servlets/AssignmentServlet.java
  capstone-backend/src/main/java/com/google/sps/servlets/ClubServlet.java
  capstone-backend/src/main/java/com/google/sps/servlets/CommentServlet.java
  capstone-backend/src/main/java/com/google/sps/servlets/Utility.java
  capstone-backend/src/test/java/com/google/sps/data/ClubTest.java
  capstone-backend/src/test/java/com/google/sps/data/CommunityTest.java
  capstone-backend/src/test/java/com/google/sps/data/GroupTest.java
Labels: Core Feature

#60 Update Mockito
  capstone-backend/.factorypath
  capstone-backend/pom.xml
Labels: Ready for Review, bug

#64 Change Assignments and Comments
  capstone-backend/src/main/java/com/google/sps/data/Assignment.java
  capstone-backend/src/main/java/com/google/sps/data/Club.java
  capstone-backend/src/main/java/com/google/sps/data/Comment.java
  capstone-backend/src/test/java/com/google/sps/data/ClubTest.java
Labels: Core Feature

#62 Search Servlet Add Search by Id
  capstone-backend/src/main/java/com/google/sps/data/VolumeData.java
  capstone-backend/src/main/java/com/google/sps/servlets/SearchServlet.java
  capstone-backend/src/test/java/com/google/sps/data/VolumeDataTest.java
  capstone-backend/src/test/java/com/google/sps/servlets/SearchServletTest.java
Labels: Core Feature, Ready for Review

#54 Basic BookLists Styling
  capstone-backend/src/main/java/com/google/sps/data/BookList.java
  capstone-backend/src/main/java/com/google/sps/servlets/BookListServlet.java
  capstone-backend/src/main/java/com/google/sps/servlets/UserServlet.java
  capstone-backend/src/main/java/com/google/sps/servlets/Utility.java
  capstone-backend/src/test/java/com/google/sps/data/BookListTest.java
  capstone-frontend/public/images/search_icon.png
  capstone-frontend/src/App.jsx
  capstone-frontend/src/LeftSideBar.test.js
  capstone-frontend/src/components/BookSearchList.jsx
  capstone-frontend/src/components/BookSearchTile.jsx
  capstone-frontend/src/components/CreateList.jsx
  capstone-frontend/src/components/LeftSideBar.jsx
  capstone-frontend/src/components/ListPage.js
  capstone-frontend/src/components/ListPage.jsx
  capstone-frontend/src/components/Login.jsx
  capstone-frontend/src/components/MyLists.jsx
  capstone-frontend/src/components/Navbar.jsx
  capstone-frontend/src/index.js
  capstone-frontend/src/styles/LeftSideBar.css
Labels: Core Feature, Ready for Review

#56 Add conditional button rendering to BookSearchTile Add
  capstone-frontend/src/BookSearchTile.test.js
  capstone-frontend/src/components/BookSearchTile.jsx
Labels: Core Feature

#65 Adds doGet to UserServlet
  capstone-backend/src/main/java/com/google/sps/servlets/UserServlet.java
Labels: Core Feature, Ready for Review

#70 Club page
  capstone-backend/src/main/java/com/google/sps/data/Comment.java
  capstone-frontend/src/App.jsx
  capstone-frontend/src/components/AssignmentCard.jsx
  capstone-frontend/src/components/ClubPage.jsx
  capstone-frontend/src/components/CommentCard.jsx
  capstone-frontend/src/styles/Groups.css
Labels: Core Feature

#71 Input current userID as ownerID on club creation
  capstone-frontend/src/components/CreateClub.jsx
Labels: Core Feature

#66 LeftSideBar now updates based on CreateList, Create List is now Modal
  capstone-frontend/src/App.jsx
  capstone-frontend/src/BookSearchTile.test.js
  capstone-frontend/src/LeftSideBar.test.js
  capstone-frontend/src/components/BookSearchList.jsx
  capstone-frontend/src/components/BookSearchTile.jsx
  capstone-frontend/src/components/Browse.jsx
  capstone-frontend/src/components/CreateList.jsx
  capstone-frontend/src/components/LeftSideBar.jsx
  capstone-frontend/src/components/ListPage.jsx
Labels: Core Feature, Ready for Review

#73 Implements Search on Create List Modal
  capstone-backend/src/main/java/com/google/sps/servlets/BookListServlet.java
  capstone-backend/src/main/java/com/google/sps/servlets/SearchServlet.java
  capstone-backend/src/main/java/com/google/sps/servlets/UserServlet.java
  capstone-backend/src/main/java/com/google/sps/servlets/Utility.java
  capstone-frontend/src/App.jsx
  capstone-frontend/src/components/AssignmentCard.jsx
  capstone-frontend/src/components/ClubPage.jsx
  capstone-frontend/src/components/CommentCard.jsx
  capstone-frontend/src/components/CreateList.jsx
Labels: Core Feature, Ready for Review

#75 Implements ListPage Styling
  capstone-backend/src/main/java/com/google/sps/servlets/CommentServlet.java
  capstone-backend/src/main/java/com/google/sps/servlets/UserServlet.java
  capstone-frontend/package-lock.json
  capstone-frontend/package.json
  capstone-frontend/src/components/ListPage.jsx
  capstone-frontend/src/styles/ListPage.css
Labels: Core Feature, Ready for Review

#76 Book Page
  capstone-frontend/src/App.jsx
  capstone-frontend/src/BookSearchTile.test.js
  capstone-frontend/src/components/BookListAddDropdown.jsx
  capstone-frontend/src/components/BookPage.js
  capstone-frontend/src/components/BookPage.jsx
  capstone-frontend/src/components/BookSearchTile.jsx
  capstone-frontend/src/styles/Book.css
  capstone-frontend/src/styles/BookSearchTile.css
Labels: Ready for Review

#69 BookSearchTile Test Updates
  capstone-frontend/src/BookSearchTile.test.js
Labels: Ready for Review

#83 Fix date bug
  capstone-frontend/src/components/AssignmentCard.jsx
  capstone-frontend/src/components/CommentCard.jsx
Labels: Core Feature

#82 Club Page: UserCards, Admin Page, Styling
  capstone-frontend/src/App.jsx
  capstone-frontend/src/components/AdminClubPage.jsx
  capstone-frontend/src/components/AssignmentCard.jsx
  capstone-frontend/src/components/ClubPage.jsx
  capstone-frontend/src/components/UserCard.jsx
  capstone-frontend/src/styles/Groups.css
Labels: Core Feature

#87 Book Thumbnail Link
  capstone-backend/src/main/java/com/google/sps/servlets/SearchServlet.java
  capstone-backend/src/test/java/com/google/sps/servlets/SearchServletTest.java
Labels: Additional Feature

#89 Landing Page
  capstone-frontend/src/App.jsx
  capstone-frontend/src/App.test.jsx
  capstone-frontend/src/BookSearchTile.test.js
  capstone-frontend/src/LeftSideBar.test.js
  capstone-frontend/src/components/ListPage.jsx
  capstone-frontend/src/components/Login.jsx
  capstone-frontend/src/components/Logout.jsx
  capstone-frontend/src/components/Navbar.jsx
  capstone-frontend/src/styles/Login.css
  capstone-frontend/src/styles/Logout.css
Labels: Core Feature, Ready for Review, enhancement

#91 ClubPage Styling
  capstone-frontend/src/components/AssignmentCard.jsx
  capstone-frontend/src/components/CommentCard.jsx
  capstone-frontend/src/styles/Groups.css
Labels: Core Feature

#97 SearchBookModal in ClubPage
  capstone-frontend/src/components/ClubPage.jsx
  capstone-frontend/src/components/SearchBookModal.jsx
  capstone-frontend/src/styles/Groups.css
Labels: Core Feature

#101 Request to join Clubs - Owner can reject and accept members
  capstone-backend/src/main/java/com/google/sps/data/Club.java
  capstone-backend/src/main/java/com/google/sps/data/Community.java
  capstone-backend/src/main/java/com/google/sps/data/Group.java
  capstone-frontend/src/App.jsx
  capstone-frontend/src/ClubGridItem.test.js
  capstone-frontend/src/components/AdminClubPage.jsx
  capstone-frontend/src/components/ClubGridItem.jsx
  capstone-frontend/src/components/ClubPage.jsx
  capstone-frontend/src/components/MyClubs.jsx
  capstone-frontend/src/components/UserCard.jsx
Labels: Core Feature

#92 Book Page Link Integration
  capstone-frontend/src/BookSearchTile.test.js
  capstone-frontend/src/components/BookDescriptionOverlay.jsx
  capstone-frontend/src/components/BookPage.jsx
  capstone-frontend/src/components/BookSearchTile.jsx
  capstone-frontend/src/components/CreateList.jsx
  capstone-frontend/src/components/ListPage.jsx
  capstone-frontend/src/components/SearchBookModal.jsx
  capstone-frontend/src/styles/Book.css
Labels: Core Feature, Ready for Review

#99 Fix rerendering of Browse page on Search Nav update
  capstone-frontend/src/components/BookSearchList.jsx
Labels: Ready for Review, bug

#100 Navbar and LeftSideBar Refactoring
  capstone-frontend/package-lock.json
  capstone-frontend/package.json
  capstone-frontend/public/manifest.json
  capstone-frontend/src/App.css
  capstone-frontend/src/App.jsx
  capstone-frontend/src/App.test.jsx
  capstone-frontend/src/BookSearchTile.test.js
  capstone-frontend/src/LeftSideBar.test.js
  capstone-frontend/src/components/BookDescriptionOverlay.jsx
  capstone-frontend/src/components/ClubPage.jsx
  capstone-frontend/src/components/CreateClub.jsx
  capstone-frontend/src/components/CreateList.jsx
  capstone-frontend/src/components/LeftSideBar.jsx
  capstone-frontend/src/components/Logout.jsx
  capstone-frontend/src/components/MyClubs.jsx
  capstone-frontend/src/components/Navbar.jsx
  capstone-frontend/src/components/RightSideBar.js
  capstone-frontend/src/components/RightSideBar.jsx
  capstone-frontend/src/components/SearchBookModal.jsx
  capstone-frontend/src/styles/LeftSideBar.css
  capstone-frontend/src/styles/Logout.css
  capstone-frontend/src/styles/Modal.css
Labels: Core Feature, Ready for Review, enhancement

#105 Better UX for CreateList Modal
  capstone-frontend/src/components/BookListAddDropdown.jsx
  capstone-frontend/src/components/CreateList.jsx
Labels: Additional Feature, Ready for Review, enhancement

#104 Friend Feature
  capstone-backend/src/main/java/com/google/sps/servlets/UserServlet.java
  capstone-frontend/src/components/UserCard.jsx
Labels: Core Feature

#110 Search Servlet - Thumbnail Fix
  capstone-backend/src/main/java/com/google/sps/servlets/SearchServlet.java
  capstone-backend/src/test/java/com/google/sps/servlets/SearchServletTest.java
  capstone-frontend/src/components/BookPage.jsx
Labels: Ready for Review, bug

#107 Initial SearchUserModal implementation
  capstone-backend/src/main/java/com/google/sps/servlets/UserSearchServlet.java
  capstone-backend/src/main/java/com/google/sps/servlets/UserServlet.java
  capstone-frontend/src/App.jsx
  capstone-frontend/src/components/Home.js
  capstone-frontend/src/components/SearchBookModal.jsx
  capstone-frontend/src/components/SearchUserModal.jsx
  capstone-frontend/src/styles/SearchUserModal.css
Labels: Core Feature, Ready for Review, enhancement

#112 Add Guava Dependency to fix backend breaking
  capstone-backend/pom.xml
Labels: Core Feature, Ready for Review, bug

#109 Fix mobile ClubGridItems and UserCards
  capstone-frontend/src/components/ClubGridItem.jsx
  capstone-frontend/src/components/UserCard.jsx
Labels: enhancement

#106 Updated Browse, Club Search Page
  capstone-backend/src/main/java/com/google/sps/servlets/ClubServlet.java
  capstone-frontend/src/App.jsx
  capstone-frontend/src/components/BookPage.jsx
  capstone-frontend/src/components/BookSearchList.jsx
  capstone-frontend/src/components/BookSearchTile.jsx
  capstone-frontend/src/components/Browse.jsx
  capstone-frontend/src/components/ClubSearchList.jsx
  capstone-frontend/src/components/LeftSideBar.jsx
  capstone-frontend/src/styles/Book.css
Labels: Core Feature, Ready for Review

#111 Collaborators Implementation for BookLists
  capstone-frontend/src/App.jsx
  capstone-frontend/src/App.test.jsx
  capstone-frontend/src/LeftSideBar.test.js
  capstone-frontend/src/components/CreateList.jsx
  capstone-frontend/src/components/LeftSideBar.jsx
  capstone-frontend/src/components/ListPage.jsx
  capstone-frontend/src/components/SearchBookModal.jsx
  capstone-frontend/src/components/SearchUserModal.jsx
  capstone-frontend/src/styles/ListPage.css
Labels: Core Feature, Ready for Review, enhancement

#114 Finish books
  capstone-backend/.factorypath
  capstone-backend/src/main/java/com/google/sps/data/Book.java
  capstone-backend/src/main/java/com/google/sps/servlets/BookServlet.java
  capstone-backend/src/test/java/com/google/sps/data/BookTest.java
  capstone-frontend/src/BookSearchTile.test.js
  capstone-frontend/src/components/BookListAddDropdown.jsx
  capstone-frontend/src/components/BookSearchList.jsx
  capstone-frontend/src/components/BookSearchTile.jsx
  capstone-frontend/src/components/ListPage.jsx
Labels: Core Feature
