Repository STEP-Pod-Capstone-Project/Capstone-Project, pull requests merged in 2020-08, with the labels that each got.

#115 Browse - User Search Page
  capstone-frontend/src/components/Browse.jsx
  capstone-frontend/src/components/UserCard.jsx
  capstone-frontend/src/components/UserSearchList.jsx
Labels: Core Feature, Ready for Review

#117 Home Page
  capstone-backend/pom.xml
  capstone-frontend/src/App.jsx
  capstone-frontend/src/BookSearchTile.test.js
  capstone-frontend/src/components/ClubGridItem.jsx
  capstone-frontend/src/components/ClubPage.jsx
  capstone-frontend/src/components/CreateList.jsx
  capstone-frontend/src/components/Home.js
  capstone-frontend/src/components/Home.jsx
  capstone-frontend/src/components/LeftSideBar.jsx
  capstone-frontend/src/components/ListPage.jsx
  capstone-frontend/src/components/MyClubs.jsx
  capstone-frontend/src/components/SearchBookModal.jsx
  capstone-frontend/src/components/SearchUserModal.jsx
  capstone-frontend/src/styles/Groups.css
  capstone-frontend/src/styles/Home.css
Labels: Core Feature, Ready for Review

#118 Handling SearchServlet Empty Response
  capstone-backend/src/main/java/com/google/sps/servlets/SearchServlet.java
  capstone-frontend/src/components/BookSearchList.jsx
  capstone-frontend/src/components/Browse.jsx
  capstone-frontend/src/components/ClubSearchList.jsx
  capstone-frontend/src/components/CreateList.jsx
  capstone-frontend/src/components/SearchBookModal.jsx
Labels: bug

#116 Assignment Due Date
  capstone-frontend/package-lock.json
  capstone-frontend/package.json
  capstone-frontend/src/components/ClubPage.jsx
Labels: Core Feature

#119 Club Meetings
  capstone-backend/.factorypath
  capstone-backend/pom.xml
  capstone-backend/src/main/java/com/google/sps/data/Meeting.java
  capstone-backend/src/main/java/com/google/sps/servlets/MeetingServlet.java
  capstone-backend/src/main/java/com/google/sps/servlets/Utility.java
  capstone-frontend/src/components/AdminClubPage.jsx
  capstone-frontend/src/components/Login.jsx
  package-lock.json
Labels: Core Feature

#124 Leave club
  capstone-frontend/src/components/ClubPage.jsx
Labels: Core Feature

#125 Remove unnecessary alerts, use console logs instead
  capstone-frontend/src/components/AdminClubPage.jsx
  capstone-frontend/src/components/AssignmentCard.jsx
  capstone-frontend/src/components/BookPage.jsx
  capstone-frontend/src/components/Browse.jsx
  capstone-frontend/src/components/ClubGridItem.jsx
  capstone-frontend/src/components/ClubPage.jsx
  capstone-frontend/src/components/ClubSearchList.jsx
  capstone-frontend/src/components/CommentCard.jsx
  capstone-frontend/src/components/ListPage.jsx
  capstone-frontend/src/components/MyClubs.jsx
  capstone-frontend/src/components/SearchBookModal.jsx
  capstone-frontend/src/components/SearchUserModal.jsx
  capstone-frontend/src/components/UserCard.jsx
Labels: bug

#128 Club Page no data behavior
  capstone-frontend/src/components/ClubPage.jsx
Labels: Core Feature

#122 Event frontend
  capstone-backend/src/main/java/com/google/sps/data/Meeting.java
  capstone-backend/src/main/java/com/google/sps/servlets/MeetingServlet.java
  capstone-frontend/package-lock.json
  capstone-frontend/package.json
  capstone-frontend/src/components/AdminClubPage.jsx
  capstone-frontend/src/components/ClubPage.jsx
  capstone-frontend/src/components/MeetingCard.jsx
  capstone-frontend/src/components/MyClubs.jsx
  capstone-frontend/src/styles/Groups.css
Labels: Core Feature

#123 Format Dates
  capstone-frontend/src/components/AssignmentCard.jsx
  capstone-frontend/src/components/CommentCard.jsx
  capstone-frontend/src/components/MeetingCard.jsx
Labels: enhancement

#121 Members Functionality for SearchUserModal
  capstone-backend/.factorypath
  capstone-backend/src/main/java/com/google/sps/servlets/UserServlet.java
  capstone-frontend/src/components/AdminClubPage.jsx
  capstone-frontend/src/components/ClubPage.jsx
  capstone-frontend/src/components/Home.jsx
  capstone-frontend/src/components/ListPage.jsx
  capstone-frontend/src/components/SearchBookModal.jsx
  capstone-frontend/src/components/SearchUserModal.jsx
Labels: Additional Feature

#120 MyBooks Page
  capstone-frontend/src/components/BookListAddDropdown.jsx
  capstone-frontend/src/components/BookPage.jsx
  capstone-frontend/src/components/LeftSideBar.jsx
  capstone-frontend/src/components/MyBooks.js
  capstone-frontend/src/components/MyBooks.jsx
Labels: Ready for Review

#133 Speed up load time
  capstone-backend/.factorypath
  capstone-frontend/src/components/AdminClubPage.jsx
  capstone-frontend/src/components/ClubPage.jsx
  capstone-frontend/src/components/MyClubs.jsx
Labels: enhancement

#136 Kick out non-members
  capstone-frontend/src/components/ClubPage.jsx
Labels: Core Feature

#138 Updating Favicon
  capstone-frontend/public/favicon.ico
  capstone-frontend/public/index.html
Labels: Ready for Review

#130 Invite to Clubs Features Frontend
  capstone-backend/src/main/java/com/google/sps/servlets/UserServlet.java
  capstone-frontend/src/LeftSideBar.test.js
  capstone-frontend/src/components/ClubPage.jsx
  capstone-frontend/src/components/Home.jsx
  capstone-frontend/src/components/LeftSideBar.jsx
  capstone-frontend/src/components/MyClubs.jsx
  capstone-frontend/src/components/SearchBookModal.jsx
  capstone-frontend/src/components/SearchUserModal.jsx
  capstone-frontend/src/components/ShowClubInvitesModal.jsx
  capstone-frontend/src/styles/Groups.css
Labels: Additional Feature, Ready for Review

#134 Manage Booklist Modal
  capstone-frontend/src/components/BookSearchTile.jsx
  capstone-frontend/src/components/LeftSideBar.jsx
  capstone-frontend/src/components/ListPage.jsx
  capstone-frontend/src/components/UpdateList.jsx
Labels: Ready for Review

#129 Right Sidebar - Friends
  capstone-frontend/src/App.jsx
  capstone-frontend/src/App.test.jsx
  capstone-frontend/src/LeftSideBar.test.js
  capstone-frontend/src/components/AdminClubPage.jsx
  capstone-frontend/src/components/Browse.jsx
  capstone-frontend/src/components/ClubPage.jsx
  capstone-frontend/src/components/LeftSideBar.jsx
  capstone-frontend/src/components/RightSideBar.jsx
  capstone-frontend/src/components/UserCard.jsx
  capstone-frontend/src/components/UserSearchList.jsx
Labels: Core Feature, Ready for Review

#140 Handle clubs without books on MyClubs page
  capstone-frontend/src/components/MyClubs.jsx
Labels: Core Feature

#142 Comment out add member button on CreateClub page
  capstone-frontend/src/components/CreateClub.jsx
Labels: Core Feature

#143 Club Styling
  capstone-frontend/src/components/AdminClubPage.jsx
  capstone-frontend/src/components/ClubPage.jsx
Labels: enhancement

#145 User Modals fix
  capstone-frontend/src/components/SearchUserModal.jsx
  capstone-frontend/src/components/ShowClubInvitesModal.jsx
Labels: Additional Feature

#147 Synchronize delete of club members and Possible Login fix
  capstone-frontend/src/LeftSideBar.test.js
  capstone-frontend/src/components/ClubPage.jsx
  capstone-frontend/src/components/Login.jsx
  capstone-frontend/src/components/SearchUserModal.jsx
Labels: Additional Feature, Ready for Review, bug

#148 Login for mobile Styling changes
  capstone-frontend/src/App.jsx
  capstone-frontend/src/components/Login.jsx
  capstone-frontend/src/styles/Login.css
Labels: Additional Feature, Ready for Review, enhancement

#150 Mobile styling
  capstone-frontend/src/components/AssignmentCard.jsx
  capstone-frontend/src/components/ClubPage.jsx
  capstone-frontend/src/styles/Groups.css
Labels: enhancement

#154 Update User Token Security
  capstone-backend/src/main/java/com/google/sps/data/Meeting.java
  capstone-backend/src/main/java/com/google/sps/servlets/MeetingServlet.java
  capstone-backend/src/main/java/com/google/sps/servlets/UserServlet.java
  capstone-frontend/src/App.jsx
  capstone-frontend/src/components/AdminClubPage.jsx
  capstone-frontend/src/components/LeftSideBar.jsx
  capstone-frontend/src/components/Login.jsx
  capstone-frontend/src/components/Logout.jsx
  capstone-frontend/src/components/MeetingCard.jsx
Labels: Core Feature
